### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/furiosa-models#118]
We need to update the followings:
* Add 0.8.1 release to `Releases` section in README.md
* Use full URLs rather than relative path in README.md
  * Please check out the links in https://pypi.org/project/furiosa-models/0.8.1/.

**Comment by furiosamg** [comment]
Since PYPI doesn't allow re-releasing package, we should fix these broken links and publish furiosa-models version 0.8.2. Is it ok?

**Comment by hyunsik** [comment]
@furiosamg Sure, as long as the release doesn't include any breaking change, we can do the minor release any time.
